### ISSUE TITLE
Update to NxNrwl 15

### ISSUE THREAD

**Issue by spaceribs** [gioragutt/nx-pwm#20]
Please make this compatible with the newest version of Nx 👍

**Comment by gioragutt** [comment]
Sure thing. Are you (thinking about) using nx-pwm?

**Comment by gioragutt** [comment]
@spaceribs version 0.5.0 was published, please let me know if it works for you 👍🏻

It is updated to version 15.2.4 of NX.

**Comment by spaceribs** [comment]
> Sure thing. Are you (thinking about) using nx-pwm?

Yes! actually I'm already using it (with --legacy-peer-deps) on https://github.com/spaceribs/spaceribs, just my attempt at making a central monorepo for my npm packages. I'll test this tomorrow and let you know!

**Comment by spaceribs** [comment]
The upgrade appears to be working! thank you

**Comment by gioragutt** [comment]
@spaceribs awesome! I'd appreciate if you let me know (here in the issue or in the NX Slack) how you use it :) I've not touched nx-pwm for a while now (since I stopped working for the company for which I developed it), but I'd be happy to support it further!
